title: My favorite game.
author: Mm_mM
email: secret@mail.ru
description: > # this means to ignore newlines until "baseurl:"

# social links
github_username:  Markop89 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
